---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cert-example
spec:
  revisionHistoryLimit: 5
  replicas: 1
  selector:
    matchLabels:
      app: cert-example
  template:
    metadata:
      labels:
        app: cert-example
    spec:
      containers:
      - name: cert-example
        image: gcr.io/kubernetes-dev-211403/cert-example:1.0
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 30080
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /
            port: 30080
            scheme: HTTP
        ports:
        - containerPort: 30080
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: cert-example
spec:
  type: NodePort
  ports:
  - port: 30080
    nodePort: 30080
  selector:
    app: cert-example

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myapp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    # ingress.kubernetes.io/rewrite-target: /
    # certmanager.k8s.io/cluster-issuer: letsencrypt-staging
spec:
  # tls:
  # - hosts:
  #   - casual-encounters.io
  #   secretName: cert-example-crt
  rules:
    - http:
        paths:
        - path: /
          backend:
            serviceName: cert-example
            servicePort: 30080
