---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cert-example
spec:
  revisionHistoryLimit: 5
  replicas: 1
  selector:
    matchLabels:
      app: cert-example
  template:
    metadata:
      labels:
        app: cert-example
    spec:
      containers:
      - name: example-nodejs1
        image: gcr.io/kubernetes-dev-211403/example-nodejs1:1.0
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 30001
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /
            port: 30001
            scheme: HTTP
        ports:
        - containerPort: 30001
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: cert-example
spec:
  type: NodePort
  ports:
  - port: 30001
    nodePort: 30001
  selector:
    app: cert-example

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cert-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    # ingress.kubernetes.io/rewrite-target: /
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
spec:
   tls:
   - hosts:
     - casual-encounters.io
     secretName: cert-example-crt
  rules:
    - http:
        paths:
        - path: /
          backend:
            serviceName: cert-example
            servicePort: 30001
