apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-nodejs
spec:
  revisionHistoryLimit: 5
  replicas: 1
  selector:
    matchLabels:
      app: example-nodejs
  template:
    metadata:
      labels:
        app: example-nodejs
    spec:
      containers:
      - name: app
        image: quay.io/jessgreb/example-nodejs:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myapp-ingress
  annotations:
    kubernetes.io/ingress.class: casual-encounters.io
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
  - hosts:
    - casualencounters.io
    secretName: example-nodejs-crt
  rules:
  - host: casualencounters.io
    http:
      paths:
      - path: /
        backend:
          serviceName: example-nodejs
          servicePort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: example-nodejs
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: example-nodejs

---
