---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: example-nodejs-crt
spec:
  secretName: example-nodejs-crt
  dnsNames:
  - casual-encounters.io
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - casual-encounters.io
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
